const test=require('node:test');const assert=require('node:assert/strict');const {openDb}=require('../src/db');const {createApp}=require('../src/app');const {categoryCandidate,updateCategory}=require('../src/bulkCategory');
test('bulk category: preview, exact candidates, filters, only category changes, invalid selection and rollback',async t=>{
 const db=openDb(':memory:');for(const title of ['[ゲーム] A','【ゲーム】 B','ゲームっぽい C'])db.prepare('INSERT INTO products(master_title) VALUES(?)').run(title);db.prepare("INSERT INTO listings(product_id,site,site_item_id,site_title,status) VALUES(1,'mercari','m1','original','unknown')").run();const categories=db.prepare('SELECT * FROM management_categories').all();assert.equal(categoryCandidate('[ゲーム] A',categories).id,1);assert.equal(categoryCandidate('【ゲーム】 B',categories).id,1);for(const title of ['[ゲーム機] C','ゲーム C',' [ゲーム] C','[ ゲーム ] C'])assert.equal(categoryCandidate(title,categories),null);
 const before=db.prepare('SELECT * FROM products ORDER BY id').all(),listings=db.prepare('SELECT * FROM listings').all();const server=createApp(db).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(async()=>{await new Promise(r=>server.close(r));db.close();});const base='http://127.0.0.1:'+server.address().port;const page=await(await fetch(base+'/products?category=unset&mercari=unknown')).text();assert.match(page,/FM00001/);assert.doesNotMatch(page,/FM00002/);const token=page.match(/name="_csrf" value="([^"]+)"/)[1];
 const body=()=>new URLSearchParams([['_csrf',token],['category_id','1'],['product_ids','1'],['product_ids','2'],['return_query','category=unset&yahoo=missing']]);const post=(url,data)=>fetch(base+url,{method:'POST',body:data,redirect:'manual'});
 const preview=await post('/products/bulk-category',body());assert.equal(preview.status,200);assert.match(await preview.text(),/この内容で確定/);assert.deepEqual(db.prepare('SELECT * FROM products ORDER BY id').all(),before);
 const done=await post('/products/bulk-category/confirm',body());assert.equal(done.status,303);assert.equal(done.headers.get('location'),'/products?category=unset&yahoo=missing&updated=2');assert.deepEqual(db.prepare('SELECT * FROM products ORDER BY id').all().map(p=>({...p})),before.map((p,i)=>({...p,category_id:i<2?1:null})));assert.deepEqual(db.prepare('SELECT * FROM listings').all(),listings);
 for(const entries of [[['category_id','1']],[['category_id','999'],['product_ids','1']],[['category_id','2'],['product_ids','1'],['product_ids','999']],[['category_id','1'],['product_ids','x']]])assert.equal((await post('/products/bulk-category/confirm',new URLSearchParams([['_csrf',token],...entries]))).status,400);
 assert.equal((await post('/products/bulk-category/confirm',new URLSearchParams({category_id:'1',product_ids:'3'}))).status,403);
 const after=db.prepare('SELECT * FROM products ORDER BY id').all();db.exec("CREATE TRIGGER reject_category BEFORE UPDATE ON products WHEN NEW.id=2 BEGIN SELECT RAISE(ABORT,'test'); END");assert.throws(()=>updateCategory(db,{product_ids:['1','2'],category_id:'2'}));assert.deepEqual(db.prepare('SELECT * FROM products ORDER BY id').all(),after);
 const unset=await(await fetch(base+'/products?category=unset')).text();assert.match(unset,/FM00003/);assert.doesNotMatch(unset,/FM00001/);
});
